### ISSUE TITLE
How to effectively sync multiple directories ?

### ISSUE THREAD

**Issue by gaurav-nelson** [carvel-dev/vendir#101]
I am trying to sync content from multiple directories from the same repository, however, when I use the following `yml` configuration, it fetches the repository all over again. Is there a better way to handle this?
```yml
# PS: https://carvel.dev/vendir/docs/latest/vendir-spec/

apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - modules/*
    newRootPath: modules/
  - path: ROOT/images
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - images/*
    newRootPath: images/
  - path: ROOT/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - welcome/*
    newRootPath: welcome/
  - path: _files
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - files/*
    newRootPath: files/
  - path: architecture/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - architecture/*
    newRootPath: architecture/
  - path: backup_and_restore/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - backup_and_restore/*
    newRootPath: backup_and_restore/
  - path: cli/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - cli/*
    newRootPath: cli/
  - path: configuration/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - configuration/*
    newRootPath: configuration/
  - path: installing/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - installing/*
    newRootPath: installing/
  - path: integration/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - integration/*
    newRootPath: integration/
  - path: operating/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - operating/*
    newRootPath: operating/
  - path: release_notes/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - release_notes/*
    newRootPath: release_notes/
  - path: support/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - support/*
    newRootPath: support/
  - path: upgrading/pages
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
    includePaths:
    - upgrading/*
    newRootPath: upgrading/

```

The source repository is at https://github.com/gaurav-nelson/rhacs-docs

**Comment by cppforlife** [comment]
@gaurav-nelson we currently did not include any optimization for fetching same repo multiple times. would be ideal but probably requires a bit of writing down how to best achieve it. do we just see that config is the same across multiple directories or do we introduce top level key called source that could be referenced by each directory?

**Comment by gaurav-nelson** [comment]
Surely there are multiple ways to handle  this, I like the idea of having top level source. So something like:
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
sources:
- name: source1
  type: git
  url: https://<repository-address>
  ref: <branch-name>
- name: source2
  type: git
  url: https://<repository-address>
  ref: <branch-name>
directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    source: source1
    includePaths:
    - modules/*
    newRootPath: modules/
  - path: ROOT/images
    source: source1
    includePaths:
    - images/*
    newRootPath: images/
  - path: ROOT/partials
    source: source2
    includePaths:
    - modules/*
    newRootPath: modules/
  - path: ROOT/images
    source: source2
    includePaths:
    - images/*
    newRootPath: images/

```

- Define a top level `sources` key which users can use to declare all supported sources `git`, `image`, `http`, `hg` etc.
- define a `source` key that can be used to link items to the declared sources.


OR

Have a top level source item and process all the directories for that item, then proceed with the next source and so on.

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
source:
  name: source1
  type: git
  url: https://<repository-address>
  ref: <branch-name>
directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    includePaths:
    - modules/*
    newRootPath: modules/
  - path: ROOT/images
    includePaths:
    - images/*
    newRootPath: images/
source:
  name: source2
  type: git
  url: https://<repository-address>
  ref: <branch-name>
directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    includePaths:
    - modules/*
    newRootPath: modules/
  - path: ROOT/images
    includePaths:
    - images/*
    newRootPath: images/

```

**Comment by cppforlife** [comment]
sources with a top level key seems like a right idea imho, though with slight modifications:

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config

sources:
- name: source1
  git:
    url: https://<repository-address>
    ref: <branch-name>

directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    source: source1
    includePaths:
    - modules/*
    newRootPath: modules/
```
