### ISSUE TITLE
For faster sync, add option to only download a single branch

### ISSUE THREAD

**Issue by gaurav-nelson** [carvel-dev/vendir#102]
**Describe the problem/challenge you have**
Currently, `vendir` takes long time to clone a repository. If I am after files from a specific branch it takes long time and it downloads unnecessary stuff I don't care about.

**Describe the solution you'd like**

Add an option to
- specify cloning depth
- only clone single branch 

```yml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: docs/modules
  contents:
  - path: ROOT/partials
    git:
      url: https://github.com/openshift/openshift-docs
      ref: rhacs-docs
      single-branch: true
      depth: 1
    includePaths:
    - modules/*
    newRootPath: modules/
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
