### ISSUE TITLE
k14s/image does not include git binary (as used by vendir for fetching git repos)

### ISSUE THREAD

**Issue by dj-wasabi** [carvel-dev/vendir#103]
**What steps did you take:**
[A clear and concise description steps that can be used to reproduce the problem.]

Created a vendir.yml with the following contents:
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: modules
  contents:
  - path: vnet
    git:
      url: git@<path_to_repo>/terraform-azure-vnet
      ref: main
    newRootPath: terraform-azure-vnet
  - path: scaled-set
    git:
      url: git@<path_to_repo>/terraform-azure-scaled-set
      ref: main
    newRootPath: terraform-azure-scaled-set
```
Running docker pull to make sure running on latest docker image:
```
docker pull k14s/image
Using default tag: latest
latest: Pulling from k14s/image
Digest: sha256:162ac7dbd54a5dd0d9fcdd1d815f0ec449313c4b82f5a095a20adcf61a182017
Status: Image is up to date for k14s/image:latest
docker.io/k14s/image:latest
```

Then running vendir:
```
docker run -it -v $(pwd):/data -w /data k14s/image vendir sync --tty
```
And I get the following output:
```
Fetching: modules + vnet (git from git@<path_to_repo>/terraform-azure-vnet@main)

  --> git init

Error: Syncing directory 'modules': Syncing directory 'vnet' with git contents: Fetching git repository: Git [init]: exec: "git": executable file not found in $PATH (stderr: )
```

**What happened:**

Get an error message that git is not found in path, while i follow the basic example found on https://carvel.dev/vendir/.

**What did you expect:**
That the repositories where downloaded in the `modules/vnet` and `modules/scaled-set` directories.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- vendir version (execute `vendir --version`): `vendir version 0.16.0`
- OS (e.g. from `/etc/os-release`): `Mac OSX, Ubuntu`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
