### ISSUE TITLE
vendir doesn't fallback to using docker config.json

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/vendir#115]
**What steps did you take:**

1. docker login 
1. create config.yml with the below contents:
```
config.yml:
---

apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: bundle/packages
    contents:
      - path: .
        imgpkgBundle:
          image: bundle-repo-requiring-auth-via-docker-config
          tagSelection:
            semver:
              constraints: ">=0.0.0"
        newRootPath: packages
  - path: bundle/.imgpkg
    contents:
      - path: .
        imgpkgBundle:
          image: bundle-repo-requiring-auth-via-docker-config
          tagSelection:
            semver:
              constraints: ">=0.0.0"
        newRootPath: .imgpkg
  - path: bundle/overlay
    contents:
    - path: .
      directory:
        path: manifests
```

```
vendir sync -f config.yml
```

**What happened:**
error:

```
vendir: Error: Syncing directory 'bundle/packages':
  Syncing directory '.' with imgpkgBundle contents:
    Fetching image tags:
      Imgpkg: exit status 1 (stderr: imgpkg: Error: GET https://registry/v2/bundle-repo-requiring-auth-via-docker-config/tags/list?n=1000:
  UNAUTHORIZED: unauthorized to access repository: bundle-repo-requiring-auth-via-docker-config, action: pull: unauthorized to access repository:  bundle-repo-requiring-auth-via-docker-config, action: pull
)
```

**What did you expect:**
Succeed

**Anything else you would like to add:**
from slack: https://kubernetes.slack.com/archives/CH8KCCKA5/p1633634540059000

**Environment:**

- vendir version (execute `vendir --version`): 0.23.0
- OS (e.g. from `/etc/os-release`): osx

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
