### ISSUE TITLE
githubRelease options should support downloading the source archive

### ISSUE THREAD

**Issue by voor** [carvel-dev/vendir#145]
**Describe the problem/challenge you have**
Currently github releases also include the source archive for the given tag.  Examples:
https://github.com/vmware-tanzu/carvel-vendir/archive/refs/tags/v0.26.0.tar.gz
https://github.com/vmware-tanzu/carvel-vendir/archive/refs/tags/v0.26.0.tar.gz

These are listed as `Assets` on the GitHub GUI, but are unable to be added to `assetNames` in the `githubRelease`.

**Describe the solution you'd like**
Support something that can allow referencing the source code archives in githubRelease that takes into consideration the resulting filename is dynamically generated off the tag name.  That means if somebody wanted to do something like this:
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  # Use this if you're downloading manifests directly from a location.
  - path: bundle/config/upstream
    contents:
      - path: .
        githubRelease:
          slug: aws/amazon-eks-pod-identity-webhook
          tagSelection:
            semver:
              constraints: ">=0.4.0"
          disableAutoChecksumValidation: true
          assetNames: ["*.tar.gz"]
          unpackArchive:
            path: "*.tar.gz"
        includePaths:
          - deploy/
        newRootPath: deploy/
```
They would need to refer to the assetNames and unpackArchive with wildcards, or some other kind of variable name to know when it's the source archive.

**Anything else you would like to add:**
This is currently remediated by just using `git` to pull down the given tag.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
