### ISSUE TITLE
Is contents/path not respected?

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/vendir#15]
When using this config:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
- path: k8s/eduk8s
  contents:
  - path: upstream/eduk8s
    git:
      url: https://github.com/eduk8s/eduk8s
      ref: 20.08.04.1
    includePaths:
    - resources/crds-v1/**/*
    - resources/operator/**/*
  - path: downstream/hub
    manual: {}
```

I would expect to end up with this folder structure:
```
k8s/eduk8s/upstream/eduk8s
k8s/eduk8s/downstream/hub
```

I understand the second needs to exist, since it's a manual sync, but the former is not and the resources specified in that rule end up in `k8s/eduk8s/content/...` rather than `k8s/eduk8s/upstream/eduk8s/content/...`.

I have seen the test https://github.com/k14s/vendir/blob/develop/examples/overlapping-dir/vendir.yml which confuses me as it seems to be the expected behavior. What am I missing?
