### ISSUE TITLE
Add option to unpack archive downloaded when using "http".

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/vendir#150]
**Describe the problem/challenge you have**

When downloading archive file using `http` I need the archive file to be automatically unpacked.

**Describe the solution you'd like**

The `githubRelease` option has `unpackArchive` for something similar although in that case you need to designate the file to unpack. In the case of `http`, there is only the one asset file so could get away with a single boolean flag to indicate whether download should be unpacked.

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- contents:
  path: src/wrapt
  - http:
      url: https://github.com/GrahamDumpleton/wrapt/archive/refs/heads/develop.tar.gz
      unpackArchive: true
    path: .
```

**Anything else you would like to add:**

I am assuming that once unpacked you can still use `newRootPath` so as to indicate you want the final result to only include files which existed in a subdirectory of the archive.

For example, in the archive above the top level directory it unpacks into is `wrapt-develop`. I am hoping one can do:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- contents:
  path: src/wrapt
  - http:
      url: https://github.com/GrahamDumpleton/wrapt/archive/refs/heads/develop.tar.gz
      unpackArchive: true
    path: .
  newRootPath: wrapt-develop
```

so that top level `wrapt-develop` directory in the archive is eliminated and you get just the files in it.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by GrahamDumpleton** [comment]
Note, it would be required that when unpacking the archive that the option exists to preserve execute bits.

Of note, when unpacking an archive from a `githubRelease` this doesn't happen, although there is a similar requirement for it as well to allow execute bits to be preserved.

* https://github.com/vmware-tanzu/carvel-vendir/issues/47

**Comment by joe-kimmel-vmw** [comment]
Thanks @GrahamDumpleton !  it sounds like preserving the execute mode bits could present some stumbling blocks but we'll leave that to the initial implementation exploration.

**Comment by knechtionscoding** [comment]
@GrahamDumpleton Am I missing something with http? I think this is already supported?

```
    # fetches asset over HTTP (optional)
    http:
      # asset URL (required)
      url: 
      # verification checksum (optional)
      sha256: ""
      # specifies name of a secret with basic auth details;
      # secret may include 'username', 'password' keys (optional)
      secretRef:
        # (required)
        name: my-http-auth
      # skip unpacking tar, tgz, and zip files; by default files are unpacked (optional)
      disableUnpack: false
```

from: https://carvel.dev/vendir/docs/v0.32.0/vendir-spec/

Specifically:

```
      # skip unpacking tar, tgz, and zip files; by default files are unpacked (optional)
      disableUnpack: false
```
