### ISSUE TITLE
Feature request: Support vendir to update a whole set of dependencies

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/vendir#16]
When having:
```
- path: k8s/config
  contents:
  - path: A
    git:
      url: https://github.com/config/A
      ref: master
  - path: B
    git:
      url: https://github.com/config/B
      ref: master
- path: k8s/examples
  contents:
  - path: A
    git:
      url: https://github.com/example/A
      ref: master
  - path: B
    git:
      url: https://github.com/example/B
      ref: master
  - path: C
    git:
      url: https://github.com/example/C
      ref: master
```

If one wants to update only examples, it would need to do it one by one with `vendir sync -d k8s/examples/A` then B and then C. It would be ideal to support the whole tree under examples when done via `vendir sync -d k8s/examples`.

And linked to #11 It would be ideal to support this use case for -d that doesn't save vendir.lock file as well as with an option to save the vendir.lock file.
