### ISSUE TITLE
Cache image and bundle contents

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/vendir#160]
**Describe the problem/challenge you have**
Implementation of https://github.com/vmware-tanzu/carvel-kapp-controller/issues/664

Allow the users to cache the contents of an image or bundle

**Describe the solution you'd like**
Depending on the path forward defined in https://github.com/vmware-tanzu/carvel-imgpkg/issues/390 vendir will need to change the way it invokes imgpkg.

In terms of UX for vendir will now look for an environment variable `VENDIR_CACHE_DIR` and if it is present it will check for the presence of a cache result.
When caching is present it will just copy from the cache folder to the destination.

Use Cases:
---
**Use case 1:** Copied from cache when sync happens twice
 
**Given** I have the following configuration
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: docker.io/dkalinin/consul-helm-by-digest
    image:
      url: index.docker.io/dkalinin/consul-helm@sha256:d1cdbd46561a144332f0744302d45f27583fc0d75002cba473d840f46630c9f7
    excludePaths:
    - .git/**/*
```
**When** I execute `VENDIR_CACHE_DIR=/tmp/vendir-cache vendir sync`
**Then** It should download the contents of the image
**Then** when I clear the current folder
**Then** I execute `VENDIR_CACHE_DIR=/tmp/vendir-cache vendir sync`
**And** vendir will populate the current folder with the contents that are present in `/tmp/vendir-cache/sha256-d1cdbd46561a144332f0744302d45f27583fc0d75002cba473d840f46630c9f7`

**Use case 2:** When image is not cacheable it does not save any data on the provided folder
 
**Given** I have the following configuration
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: docker.io/dkalinin/consul-helm-by-tag
    image:
      url: dkalinin/consul-helm:latest
    excludePaths:
    - .git/**/*  
```
**When** I execute `VENDIR_CACHE_DIR=/tmp/vendir-cache vendir sync`
**Then** It should download the contents of the image
**And** the folder `/tmp/vendir-cache` should be empty

**Use case 3:** When image is not cacheable and max-cacheable-size is small than the content it **does NOT** fail and nothing is cached
 
**Given** I have the following configuration
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: docker.io/dkalinin/consul-helm-by-tag
    image:
      url: dkalinin/consul-helm:latest
    excludePaths:
    - .git/**/*  
```
**When** I execute `VENDIR_CACHE_DIR=/tmp/vendir-cache VENDIR_MAX_CACHE_SIZE=1 vendir sync`
**Then** It should download the contents of the image
**And** The folder `/tmp/vendir-cache` is empty

**Anything else you would like to add:**
Depending on the implementation provided by imgpkg, vendir might need to ensure that it is backward compatible with the version of imgpkg installed in the system.

vendir should use the SHA of the image as the key to store and retrieve the contents from the folder

The default value for the Maximum size of the folder to be cached is "1Mi"

Caching folder structure:
Format expected: `.vendir-cache/fetcher/artifactType/folderWithID`
- `artifactType` is the type of artifact that is being saved in the cache. Currently, we only have `image` and `imgpkgBundle` types with this feature. 
- `folderWithID` is a normalized version of the SHA of the images being cached. In the future this definition will evolve once we introduce caching for other type of artifacts being downloaded by vendir.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.
