### ISSUE TITLE
Allow ability to not initialize git submodule

### ISSUE THREAD

**Issue by mymasse** [carvel-dev/vendir#162]
**Describe the problem/challenge you have**

We use `vendir` in an air-gapped network and have run into an issue where one repository we are trying to vendor uses git submodules. When `vendir sync` is run it tries to initialize all submodule but in our case that submodule is not available (and we actually don't need it since with also use `includePaths`).

This issue in question is from https://github.com/vmware-tanzu/carvel-vendir/blob/develop/pkg/vendir/fetch/git/git.go#L175 which always issues `submodule update --init --recurcive`.

**Describe the solution you'd like**

Would like an option to not run the `submodule update --init --recurcive`.

```yaml
    # uses git to clone Git repository (optional)
    git:
      ...
      # Initialize submodule included in the referenced repository (optional)
      initializeSubmodule: true
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
