### ISSUE TITLE
Support s3:// protocol

### ISSUE THREAD

**Issue by seanorama** [carvel-dev/vendir#176]
**Describe the problem/challenge you have**

Need to fetch artifacts from AWS S3 buckets.

We, and our vendors, distribute artifacts with S3. Some buckets are secured so can't be accessed anonymously via the `https://` path.

**Describe the solution you'd like**

Support `s3://` like this:

```yml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: my-package
    s3:
      url: s3://bucket-name/packages/my-package.tgz
```

It should use the AWS SDK, such that it automatically uses the authentication from the environment (variables, credential file, credential process, instance metadata, ...).

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
