### ISSUE TITLE
clearer error message if path for githubrelease archive does not exist

### ISSUE THREAD

**Issue by zoop-btc** [carvel-dev/vendir#184]
**What steps did you take:**
I tried to unpack a github release with the wrong archive name. Here is a vendir.yaml file to replicate:
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  # unpacks archive included in the release
  - path: github.com/cloudfoundry-incubator/eirini-release
    githubRelease:
      slug: cloudfoundry-incubator/eirini-release
      tag: v1.2.0
      checksums:
        eirini-cf.tgz: 819b37126f81ad479acc8dcd7e61e8b0e55153d8fa27aa9a04692c38d0c310fe
        eirini-uaa.tgz: efe8a498c67368fac1c46fa52c484261cbf4e78b3291cff69e660cd863342674
        eirini.tgz: b535d9434300e79d11d42acc417148d09054aa32808dab5f12264d3af59ad548
      unpackArchive:
        path: thisfiledoesnotexist.tgz
```

**What happened:**
You get the error:
> vendir: Error: Syncing directory 'vendor':
  Syncing directory 'github.com/cloudfoundry-incubator/eirini-release' with github release contents:
    Expected known archive type (zip, tgz, tar)

**What did you expect:**
An error message which tells me that the specified file does not exist. Can be implemented by a check before trying to unpack it.

**Environment:**

- vendir version: 0.31.0
- OS: Debian Bookworm

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
