### ISSUE TITLE
Vendir is failing to sync a dir if the previous sync has `disableUnpack: true`

### ISSUE THREAD

**Issue by kumaritanushree** [carvel-dev/vendir#189]
**What steps did you take:**
Tried to sync dir with the configuration :
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: k8s-simple-app-plain
    http:
      url: https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip

  - path: k8s-simple-app-digested
    http:
      url: https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip
      sha256: "82685cca45be6b93deb929debe1513cc73110af2f1d4a00b9d0f18f20a104a98"
      disableUnpack: true

  - path: k8s-simple-app-archived
    http:
      url: https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip
      disableUnpack: true
```
**What happened:**
Vendir is throwing error:
```
$ vendir sync    
Fetching: vendor + k8s-simple-app-plain (http from https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip)

Fetching: vendor + k8s-simple-app-digested (http from https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip)

Fetching: vendor + k8s-simple-app-archived (http from https://dk-shared-assets.s3.amazonaws.com/k8s-simple-app-example-master.zip)

vendir: Error: Syncing directory 'vendor':
  Syncing directory 'k8s-simple-app-archived' with HTTP contents: open .vendir-tmp/incoming/vendir-http2657742031: no such file or directory
```

**What did you expect:**
Vendir is renaming path `.vendir-tmp/incoming`  ( created internally by vendir to perform operations) and due to which vendir is not able to find the dir `.vendir-tmp/incoming/` in the next sync and throwing this error.

Need to have a special handling of this temporary dir in case of  `disableUnpack: true`.

**Anything else you would like to add:**

**Environment:**

- vendir version (execute `vendir --version`):  vendir version 0.30.0
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help work on this issue.
