### ISSUE TITLE
Bug: Paths don't allow using path names that starts with a string that is used in other path names

### ISSUE THREAD

**Issue by aknysh** [carvel-dev/vendir#21]
## what
* Bug: Paths don't allow using path names that starts with a string that is used in other path names

## why

We use the following configuration in `vendir.yml`:

```
  - path: components/terraform
    contents:
      - path: account-map
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account-map
        includePaths:
          - modules/account-map/**/*

      - path: account
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account
        includePaths:
          - modules/account/**/*
```

and getting the following error:

```
Error: Parsing resource config 'vendir.yml': Unmarshaling config: Validating config: Expected to not manage overlapping paths: 'components/terraform/account-map' and 'components/terraform/account'
```

Note that `account_map` does not work either, throwing the same validation error.

Moving the folders to the top-level throws the same error as well:

```
- path: components/terraform/account-map
    contents:
      - path: .
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account-map
        includePaths:
          - modules/account-map/**/*
  - path: components/terraform/account
    contents:
      - path: .
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account
        includePaths:
          - modules/account/**/*
```

This does not work either:

```
      - path: accountmap
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account-map
        includePaths:
          - modules/account-map/**/*

      - path: account
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account
        includePaths:
          - modules/account/**/*

```

throwing the error:

```
Error: Parsing resource config 'vendir.yml': Unmarshaling config: Validating config: Expected to not manage overlapping paths: 'components/terraform/accountmap' and 'components/terraform/account'

```

But this works ok:

```
      - path: a-ccountmap
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account-map
        includePaths:
          - modules/account-map/**/*

      - path: account
        git:
          url: https://github.com/cloudposse/terraform-aws-components
          ref: 0.135.0
        newRootPath: modules/account
        includePaths:
          - modules/account/**/*
```

So the issue is that the code checks not for the full path, but if a path starts with a string.

@cppforlife can you please take a look at the issue?
We like `vendir` and want to use it in our architectures.

Thank you
