### ISSUE TITLE
Sync fails when providing the same secret more than once 

### ISSUE THREAD

**Issue by odinnordico** [carvel-dev/vendir#238]
**What steps did you take:**
[A clear and concise description steps that can be used to reproduce the problem.]

1. Create a private git repository with multiple folders to sync

```bash
repo
|- app
|--- app.yaml
|- cm
|--- cm.yaml
|- secret
|--- secret.yaml
```

3. Create the `vendir.yml` file with multiple `content` entries, each to different folder of the same repo, each entry has the `secretRef` with the same _Secret_ `name`

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: "repo"
  contents:
  - path: cm
    git:
      url: git@github.com:odinnordico/kapp-controller-private-test.git
      secretRef:
          name: ssh-key-secret
      ref: origin/main
  - path: secret
    git:
      url: git@github.com:odinnordico/kapp-controller-private-test.git
      secretRef:
          name: ssh-key-secret
      ref: origin/main
---
apiVersion: v1
data:
  ssh-privatekey: LS...o=
kind: Secret
metadata:
  creationTimestamp: null
  name: ssh-key-secret
---
apiVersion: v1
data:
  ssh-privatekey: LS...=
kind: Secret
metadata:
  creationTimestamp: null
  name: ssh-key-secret
---
apiVersion: v1
data:
  ssh-privatekey: LS...o=
kind: Secret
metadata:
  creationTimestamp: null
  name: ssh-key-secret
```

5. Run the vendir command
```bash
vendir sync 
```
6. Check the output:

```bash
Fetching: repo + app (git from git@github.com:odinnordico/kapp-controller-private-test.git@origin/main)

vendir: Error: Syncing directory 'repo':
  Syncing directory 'app' with git contents:
    Fetching git repository:
      Expected to find one secret 'ssh-key-secret', but found multiple
```

**What happened:**
[A small description of the issue]

When using the same secret to sync folders in the same private repo and providing the secret more than once, `vendir` fails expecting only one secret and not matter if it is the same

**What did you expect:**
[A description of what was expected]

The directory syncs correctly with the private git repo

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

Kapp Controller related issue: [1002](https://github.com/carvel-dev/kapp-controller/issues/1002)

**Environment:**

- vendir version (execute `vendir --version`): vendir version 0.33.1
- OS (e.g. from `/etc/os-release`):

PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
