### ISSUE TITLE
add kubernetes source

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/vendir#25]

**Comment by danielhelfand** [comment]
I am curious about this feature. Are there any more details to add on what a Kubernetes source for `vendir` means? Does this mean fetching resources from a cluster, or something different?

**Comment by cppforlife** [comment]
> Does this mean fetching resources from a cluster

yeah something like this what i had in mind:

```yaml
kubernetesResources:
  resources:
  - apiVersion: v1
    kind: Pod
    namespace: ""
    fieldSelector:
    labelSelector:
    path: all-pods.yml

  - apiVersion: v1
    kind: Secret
    namespace: ...
    fieldSelector:
    labelSelector:
      matchLabels:
        foo: ""
      matchExpressions:
      - ...
    path: svc.yml
```

main use case you be when vendir is being used by kapp-controller. it would give ability for App CR to take k8s resources in the cluster as inputs to ytt templates.
