### ISSUE TITLE
Feature request: add option for skipping SSL verification when using Git

### ISSUE THREAD

**Issue by alexandreroman** [carvel-dev/vendir#260]
**Describe the problem/challenge you have**
vendir has no option for setting `GIT_SSL_NO_VERIFY=true`, which could be used with Git repos using a self-signed certificate.
[This environment variable tells Git not to verify SSL certificates](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables).

**Describe the solution you'd like**
The current implementation already sets a few environment variables when using Git, such as `GIT_LFS_SKIP_SMUDGE=1` to [skip downloading lfs files](https://github.com/carvel-dev/vendir/blob/develop/pkg/vendir/fetch/git/git.go#L121).

I wish there was a way to disable SSL verification when using Git, by adding a flag in the Git configuration.

For example:

```yaml
git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: origin/master
      # skip SSL verification
      skipSslVerification: true
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
