### ISSUE TITLE
Failure on specific directory sync with --directory flag

### ISSUE THREAD

**Issue by fritzduchardt** [carvel-dev/vendir#277]
**What steps did you take:**

This is my vendir.yml
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/grafana
  contents:
  - path: .
    helmChart:
      name: grafana
      version: 5.5.7
      repository:
        url: https://charts.helm.sh/stable
```
I am running selective directory syncing. Of course, in my example this is not necessary, but my vendir.yml could contain multiple directories.

`vendir sync -d charts/grafana`

**What happened:**

On first sync, when there is no lock file written to my local dist, I get the following error:

`vendir: Error: Reading lock config 'vendir.lock.yml': open vendir.lock.yml: no such file or directory`

Syncing somewhat worked, but no lock file was written.

**What did you expect:**

I would expect no error message, plus a lock file containing the version of the directory that I have synced.

**Environment:**

- vendir version (execute `vendir --version`): 0.29.0
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
