### ISSUE TITLE
http fails to unpack certain tar.gz files

### ISSUE THREAD

**Issue by reegnz** [carvel-dev/vendir#285]
**What steps did you take:**

I wanted to vendor a tar.gz file fetched from github:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: sponnet
  contents:
  - path: .
    http:
      url: https://github.com/spinnaker/sponnet/archive/refs/tags/v1.26.0.tar.gz
      unpackArchive: true
```

**What happened:**
The tar.gz file was not unpacked.

**What did you expect:**
The tar.gz file should have been unpacked.

**Anything else you would like to add:**
Originally I experimented with a fix for the issue mentioned in #150.

**Environment:**

```
❯ vendir version
vendir version 0.34.3

Succeeded
```
OS: MacOS Ventura 13.5

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
