### ISSUE TITLE
Error when using --directory and --locked option at the same time

### ISSUE THREAD

**Issue by fritzduchardt** [carvel-dev/vendir#299]
**What steps did you take:**

This is my vendir.yml
```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/grafana
  contents:
  - path: .
    helmChart:
      name: grafana
      version: 5.5.7
      repository:
        url: https://charts.helm.sh/stable
```
I am trying to use the `--directory` option together with the `--locked` option.

```
vendir sync -d charts/grafana --locked
```

**What happened:**

 This always errors with:

```
vendir: Error: Expected to find directory 'nginx/custom-repo-custom-version' within lock config, but did not
```

**What did you expect:**

This should work just fine. Using the lock file for a specific directory seems a valid use case.

**Environment:**
- vendir version: 0.35.0
- Ubuntu 20.04.4

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
