### ISSUE TITLE
issue with lazy sync functionality

### ISSUE THREAD

**Issue by Sanrahul02** [carvel-dev/vendir#319]
Background:

The vendir.yml file contains the configuration lazy: true. Upon running vendir sync on a clean project, the project was updated with the vendor directory and all dependencies, along with the vendir.lock.yaml. However, running vendir sync a second time resulted in the complete clearance of the vendor/ directory.

sample vendir.yml :

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: dir
    lazy: true
    directory:
      path: ./some-content
```

What I expected:
I expected the vendir sync to skip populating the vendor directory in the second run without clearing the directory.

Environment:

Vendir version: 0.36.0
Operating System: Photon 3/5 or Ubuntu

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
