### ISSUE TITLE
Vendir directory sync ignores overlapping paths on directories

### ISSUE THREAD

**Issue by fritzduchardt** [carvel-dev/vendir#323]
**What steps did you take:**
I am running this vendir.yml with two directories that define the same root path:
```
kind: Config
directories:
- path: vendor
  contents:
  - path: dir1/output
    directory:
      path: ./local-dir
- path: vendor
  contents:
  - path: dir2/output
    directory:
      path: ./local-dir-2
```

**What happened:**
The second directory overwrites the first in the final output directory. Only dir2 appears in the final output directory.

**What did you expect:**
I would either expect an overlapping path error message, as with overlapping paths within the same directory, or I would expect both dirs to appear in the final output directory.

**Environment:**
- vendir version: 0.37.0
- Ubuntu 20.04

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
