### ISSUE TITLE
support imgpkg bundle download

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/vendir#34]
**Describe the problem/challenge you have**

want to download imgpkg bundles.

**Describe the solution you'd like**

```yaml
imgpkgBundle:
  # image URL; could be plain, tagged or digest reference (required)
  image: gcr.io/repo/image:v1.0.0
  # specifies name of a secret with registry auth details;
  # secret may include 'username', 'password' and/or 'token' keys (optional)
  secretRef:
    # (required)
    name: my-image-auth
```

would use imgpkg pull -b ...

TBD is is too confusing that we are using `image` for referring to bundle? mostly interested in doing that because kbld picks up `image` key automatically for image ref.

**Anything else you would like to add:**

related: should we update image source to use image key instead of url.
