### ISSUE TITLE
Vendir allows self-destructing configuration

### ISSUE THREAD

**Issue by Zebradil** [carvel-dev/vendir#348]
**What steps did you take:**

Try to run `vendir sync` with a config that contains a directory path with `..`, like this (the `charts` directory must exist beforehand):

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts/..
    contents:
      - path: foo
        inline:
          paths:
            test.txt: hello world
```

**What happened:**

All files from the current directory are gone.

```
❯ vendir sync
Fetching: charts/.. + foo (inline)

vendir: Error: Syncing directory 'charts/..':
  Deleting dir charts/..: unlinkat charts/..: directory not empty

❯ ls -la | wc -l
0
```

**What did you expect:**

I expect vendir to complain about the faulty configuration, like it does for the `.` path:

```
❯ cat <<EOF | vendir sync -f-
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: .
    contents:
      - path: foo
        inline:
          paths:
            test.txt: hello world
EOF
vendir: Error: Parsing resource config '-':
  Unmarshaling config:
    Validating config:
      Validating directory '.' (0):
        Expected path to not be one of '/', '.', '..', ''
```

**Environment:**

- vendir version: 0.38.0
- OS: latest Arch Linux x86_64

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
