### ISSUE TITLE
Feature request: support flag to disable UnpackArchive

### ISSUE THREAD

**Issue by vvicaretti** [carvel-dev/vendir#40]
**Describe the problem/challenge you have**
When the target is a zip file, vendir automatically unzip it.
It would be nice to introduce a flag to disable this behavior. 

**Describe the solution you'd like**
Example:
```
      - path: artifacts/plugins/myplugin.zip
        http:
          url: https://artifacts.example.com/downloads/plugins/myplugin.zip
          unpackArchive: false
```

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]
