### ISSUE TITLE
Cannot Exclude '.git' folder when vendoring top-level of git repo

### ISSUE THREAD

**Issue by BronzeDeer** [carvel-dev/vendir#408]
**What steps did you take:**
Vendor a repository from git with `**/*`  or empty includePaths and excludePaths set to `.git/`.

**What happened:**
the .git folder was present in the vendored folder, causing git to detect a sub-project and storing metadata of the vendored project

**What did you expect:**
the `.git` folder not being copied to the vendored folder, hiding git metadata of the vendored repository

**Anything else you would like to add:**
I also tried various other combinations for specifing the git folder including postfixing with `**/*`, prefixing with the content path, omitting the trailing slash, prefixing with `./` etc

**Environment:**

- vendir version (execute `vendir --version`): 0.43.0
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04.1 LTS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by Zebradil** [comment]
Hey @BronzeDeer,

Thank you for filing the issue. Could you please provide a minimal vendir configuration to reproduce the issue?

**Comment by BronzeDeer** [comment]
> Hey [@BronzeDeer](https://github.com/BronzeDeer),
> 
> Thank you for filing the issue. Could you please provide a minimal vendir configuration to reproduce the issue?

Here's a minimal config

```yaml

apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  - path: vendor/vendir/

    contents:
    - path: .
      git:
        url: https://github.com/carvel-dev/vendir
        ref: origin/v0.43.1
        excludeFiles:
          - .git/**/*
```

```sh
$ vendir sync
```
 Actual:
```sh
$ ls -1 vendor/vendir/.git

config
description
FETCH_HEAD
HEAD
hooks
index
info
logs
objects
refs
```

Expected:
```sh
$ ls -1 vendor/vendir/.git

ls: cannot access 'vendor/vendir/.git': No such file or directory
```

**Comment by joaopapereira** [comment]
Can you try the following configuration:
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  - path: vendor/vendir/

    contents:
    - path: .
      git:
        url: https://github.com/carvel-dev/vendir
        ref: origin/v0.43.1
      excludePaths:
          - .git/**/*
```

```
❯ ll vendor/vendir/.git
ls: vendor/vendir/.git: No such file or directory
```

Using `directories[].contents[].excludePaths` should give you what you want.
