### ISSUE TITLE
Error when using vendir sync

### ISSUE THREAD

**Issue by vincent-hatakeyama** [carvel-dev/vendir#418]
**What steps did you take:**

I run `vendir sync` with the following file (in an otherwise empty directory):

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: github.com
    contents:
      - path: OCA/l10n-france
        git:
          url: https://github.com/OCA/l10n-france.git
          ref: "17.0"
````

**What happened:**

vendir returns error code 1, with this message:

`vendir: Error: Unable to resolve symlink: lstat github.com/OCA/l10n-france-git/l10n_fr_ecotaxe: no such file or directory`

**What did you expect:**

I expected no error and the git clone to work and put the repository in github.com/OCA/l10n-france.

**Anything else you would like to add:**

I’ve add the issue since several version of vendir, at least 0.40.

Another colleague reproduces the issue.

**Environment:**

- vendir version (execute `vendir --version`): 0.43.2
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 12 (bookworm)
- git : 2.39.5 (this is the standard version of bookworm)
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
