### ISSUE TITLE
Vendir should preserve execution permissions on extract

### ISSUE THREAD

**Issue by braunsonm** [carvel-dev/vendir#47]
**What steps did you take:**

```yaml
- path: terraform.d/plugins
  contents:
  - path: carvel.dev/carvel/k14s/0.6.0
    githubRelease:
      slug: vmware-tanzu/terraform-provider-carvel
      tag: v0.6.0
      assetNames: ["terraform-provider-k14s-binaries.tgz"]
      unpackArchive:
        path: terraform-provider-k14s-binaries.tgz
```

`vendir sync`

**What happened:**
The extracted package binaries will be set as non-executable even though in the archive they are executable.

**What did you expect:**
The file permissions should be left alone and they should be executable.

**Anything else you would like to add:**
This is very important for downloading of CLI tools

**Environment:**

- vendir version (execute `vendir --version`): 0.13.0
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04
