### ISSUE TITLE
Symlinks aren't properly copied

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/vendir#57]
**What steps did you take:**
`vendir sync` with this config:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/upstream
  contents:
  - path: serving
    git:
      url: https://github.com/knative/serving
      ref: v0.21.0
    includePaths:
    - config/core/**/*
```

**What happened:**
`config/upstream/serving/config/core/300-imagecache.yaml` is an invalid symlink, pointing to a file that doesn't exist.

**What did you expect:**
I'm not 100% sure, probably it should collapse the symlink into a regular file with the contents of the file it pointed to. Maybe this needs to be configurable.

**Anything else you would like to add:**
I looked into this a little and found it was broken in the library that vendir depends on: https://github.com/otiai10/copy/issues/32

**Environment:**

- vendir version (execute `vendir --version`): 0.16.0
- OS (e.g. from `/etc/os-release`): ubuntu focal
