### ISSUE TITLE
vendir downloads helm charts to c:\windows

### ISSUE THREAD

**Issue by meier-christoph** [carvel-dev/vendir#67]
**What steps did you take:**

I am using the carvel suite with helm on windows. Any helm chart should be able to reproduce the issue.

```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: kube-prometheus
        helmChart:
          name: kube-prometheus
          version: 5.0.0
          repository:
            url: https://charts.bitnami.com/bitnami
```

**What happened:**

```
Error: Syncing directory 'vendor': Syncing directory 'kube-prometheus' with helm chart contents: Fetching helm chart: exit status 1 (stderr: Error: failed to untar: mkdir C:\WINDOWS\helm-741980851: Access is denied.)
```

**What did you expect:**

It should use the `.vendir-tmp` dir relative to the current dir or use `~/.cache/vendir` or event `/tmp` or `C:\Users\{user}\AppData\Local\Temp`

**Environment:**

- vendir version (execute `vendir --version`): v0.19.0
- OS (e.g. from `/etc/os-release`): Windows 10

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
