### ISSUE TITLE
support a way to download subset of github release assets

### ISSUE THREAD

**Issue by jamespollard8** [carvel-dev/vendir#7]
In cf-for-k8s, we'd like to remove `disableAutoChecksumValidation: true` from our entry for kpack, for example.

That block looks like this:
```
  - path: github.com/pivotal/kpack
    githubRelease:
      slug: pivotal/kpack
      tag: v0.0.8
      disableAutoChecksumValidation: true
    includePaths:
    - release-0.0.8.yaml
```

And when we remove the `disableAutoChecksumValidation` line, we get the error:

`Error: Syncing directory 'config/_ytt_lib': Syncing directory 'github.com/pivotal/kpack' with github release contents: Finding checksums in release notes: Expected to find sha256 checksum for file 'logs-v0.0.8-linux.tgz'`

...even though the only file in our include path is `release-0.0.8.yaml`.

Here's the kpack release page in case that's helpful: https://github.com/pivotal/kpack/releases/tag/v0.0.8
