### ISSUE TITLE
Utilize caching when fetching similar repos

### ISSUE THREAD

**Issue by iliazlobin** [carvel-dev/vendir#80]
**Describe the problem/challenge you have**
When it comes to using [overlapping sync options](https://github.com/vmware-tanzu/carvel-vendir/tree/develop/examples/overlapping-dir), it's usually that you would mention the same repo to pull from several times in order to substitute one of the folders with a custom one from the private repo, for instance:
```
directories:
  - path: components
    contents:
      - path: terraform/tfstate-backend
        git:
          url: git@github.com:cloudpossy/terraform-aws-components.git
          ref: all-new-components
        newRootPath: modules/tfstate-backend
      - path: terraform/account
        git:
          url: git@github.com:cloudpossy/terraform-aws-components.git
          ref: all-new-components
        newRootPath: modules/account
      - path: terraform/account-map
        git:
          url: git@github.com:cloudpossy/terraform-aws-components.git
          ref: all-new-components
        newRootPath: modules/account-map
      - path: terraform/nexus
        git:
          url: git@github.com:privateorg/terraform-aws-components.git
          ref: atmos-novel
        newRootPath: privateorg/modules/nexus
```

Here where it gets too long to wait when `vendir sync` is used because it basically tries to react on that planly by downloading `git@github.com:cloudpossy/terraform-aws-components.git` every time it's mentioned in the spec without attempting to re-use the cached sample.

I'd guess, that it's something of utmost importance to implement this simple functionality and make the tool much more efficient.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
